name: Security Check

on:
  pull_request_target:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

permissions:
  contents: read
  issues: write
  pull-requests: write
  security-events: write
  actions: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run npm audit
        id: audit
        run: |
          pnpm audit --audit-level moderate --json > audit-results.json || true
          echo "audit_results=$(cat audit-results.json)" >> $GITHUB_OUTPUT

      - name: Check for vulnerabilities
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            let auditResults = {};
            
            try {
              const auditData = fs.readFileSync('audit-results.json', 'utf8');
              auditResults = JSON.parse(auditData);
            } catch (error) {
              console.log('No audit results found or error parsing JSON');
              return;
            }

            if (auditResults.metadata && auditResults.metadata.vulnerabilities) {
              const vulns = auditResults.metadata.vulnerabilities;
              const totalVulns = vulns.moderate + vulns.high + vulns.critical;
              
              if (totalVulns > 0 && context.eventName === 'pull_request') {
                const message = `🚨 **Security Audit Found Issues**\n\n` +
                  `- **Critical**: ${vulns.critical}\n` +
                  `- **High**: ${vulns.high}\n` +
                  `- **Moderate**: ${vulns.moderate}\n\n` +
                  `Please run \`pnpm audit fix\` to resolve these issues.`;
                
                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: message
                });
              }
            }

      - name: CodeQL Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Comment on success
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ **Security Check Passed**\n\nNo security vulnerabilities detected in dependencies and code analysis completed successfully.'
            })
